### ISSUE TITLE
First meetup! 🎉

### ISSUE THREAD

**Issue by koddsson** [nodeschool/reykjavik#2]
I'm in Berlin right now but I've [tweeted](https://twitter.com/koddsson/status/648863244275331072) the Reykjavík University about getting using some of their facilities for a first meetup. The venue is likely to be free, it has great wifi, is accessible and we've had some successful meetups there before.

Here's a trimmed down list of what I think needs to get done (once we've confirmed the RU venue):
- [x] Make a budget (it's okay to start simple as you figure things out, just start)
  - [x] To get this meetup off the ground I'm thinking to start small and not having a huge budget. I do really want to get some stickers though so I'm initially gonna go for a budget of $150 to [buy some stickermule](https://www.stickermule.com/marketplace/5544-nodeschool-international-sticker) to hand out to attendees.
- [x] Pick a date and start/end times.
- [x] Add the event to the NodeSchool site by filling out [this Google form](https://docs.google.com/forms/d/1vYW-Yw82kt_q7WDgBY6gQqFrg3zuD2rDPXEG-cbq7e4/viewform?usp=form_confirm).
- [x] Start talking to potential sponsors early to make sure you're able to secure enough funding in time. And if they can't pitch in for this event, find out if a future event is a possibility with more notice.
- [x] Reach out directly to different groups that you want to see attend. Find existing tech groups like JS meetups, women in tech groups, people of color in tech groups, gender neutral groups etc and inviting them to come and learn node. (If you don't reach out beyond who you know personally then your event will likely be less diverse, and nobody likes a monoculture.)
- [x] [Order stickers](http://hexb.in/sticker.html). Seriously, people love these. Order them early.

I'll try to keep this issue updated as I go along planning this and will make a seperate issue when it's all fleshed out and a date has been decided.

**Comment by thorsteinsson** [comment]
We've got a venue, event registration on fb & tito and ordered 100 stickers. It's now featured on nodeschool.io.
Everything is ready to run the event but it would be nice to lunch sponsored.

**Comment by thorsteinsson** [comment]
[Aranja](https://aranja.com) will sponsor this first event and we should start looking for other sponsors for future events.

**Comment by koddsson** [comment]
:tada: :tada: :tada:
