### ISSUE TITLE
Anyone around today?

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/reykjavik#3]
I'm in Iceland for a couple of days, after going to [arcticjs](//arcticjs.club) last week. Anyone around who feels like hacking in a coffee shop? In Stofan cafe for the next few hours, and should be free for a bit on Wednesday, too. 

Posting this here on the off chance people want to do some nodeschooling.

**Comment by bnvk** [comment]
@RichardLitt I also highly recommend [Reykjavik Roasters](reykjavikroasters.is/english/) good wifi, staff, and best kaffi in town :smile:

**Comment by thorgnyr** [comment]
Reykjavík Roasters doesn't have wifi anymore.

**Comment by koddsson** [comment]
I think the one at [Brautarholt](https://www.google.is/maps/@64.1418222,-21.9115305,3a,75y,168.94h,87.9t/data=!3m6!1e1!3m4!1sVI1f1BaeqE3Vo1g61K18Iw!2e0!7i13312!8i6656) does and it's bigger and a better (IMO) place to camp out at ^^

**Comment by RichardLitt** [comment]
Cool. I think I'll head there in an hour or so. Heard there is wifi there. Will keep this thread updated.

**Comment by RichardLitt** [comment]
There is totally wifi at Brautarholt RR. :+1:

**Comment by RichardLitt** [comment]
Cool. Was pretty sweet meeting @thorgnyr the other day. I'll be at Reykjavík Roasters in Brauterholt at around 10:30am. Come join if you're around, anyone! Probably heading off around 12:30.

**Comment by RichardLitt** [comment]
Turns out that @thorgnyr and I are actually doing some nodeschool walkthroughs this morning! Woo!

**Comment by thorgnyr** [comment]
Wh00p!

**Comment by bnvk** [comment]
@thorgnyr @RichardLitt damn, wish I coulda chilled with you both! I guess I just have this Sigur Ros to listen to as a consolation... :wink:

**Comment by thorgnyr** [comment]
I've become a js compositor today I guess. This is amazing!

**Comment by RichardLitt** [comment]
@bnvk one day! One day. 

This chapter of nodeschool pop up is now closed.
