### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/reykjavik#4]
We need stickers! Anyone want to design/make some?

**Comment by thorsteinsson** [comment]
We ordered stickers yesterday for our nodeschool meetup on 13th of Feb.
![12654181_926314087445812_2531166216925137037_n](https://cloud.githubusercontent.com/assets/39039/12642954/db83e960-c56d-11e5-91f4-e42b027eabc1.png)

It's just the basic Nodeschool design with RVK, we need a better design but this is good enough for the first meetup.

**Comment by RichardLitt** [comment]
Aha, sweet! Maybe changing the colors to white and blue would be good. I won't make it to the next NodeSchool there, but hope you all have fun. :)

**Comment by thorsteinsson** [comment]
Here's our new logo made by [salmon.design](http://salmon.design).

![12645221_926766867400534_2707716424718591735_n](https://cloud.githubusercontent.com/assets/39039/12659398/7abb221c-c606-11e5-9cb2-a363d3eb2e20.png)

We already ordered the other one for the first event to be able to get them before the event. The new logo will be next time.

**Comment by koddsson** [comment]
whoa, those are awesome!
