### ISSUE TITLE
Mentors on Feb meetup

### ISSUE THREAD

**Issue by thorsteinsson** [nodeschool/reykjavik#5]
Please add to the list.
- @baering
- @benediktvaldez 
- @brysbra
- @eirikurn
- @davidblurton
- @koddsson 
- @snorrid
- @thorsteinsson

**Comment by thorgnyr** [comment]
When is the feb meetup btw? I would like to come.

**Comment by thorgnyr** [comment]
Ok. Found the 13th in a different thread.- Where, then?

**Comment by thorsteinsson** [comment]
@thorgnyr We have an event on facebook: https://www.facebook.com/events/1556551801332133/

**Comment by thorsteinsson** [comment]
We now have more mentors and we're going to use a facebook to collaborate: https://www.facebook.com/groups/1697640117120426/.

We have enough mentors for the first meetup so I'm closing this issue.
